# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 15:58
from __future__ import unicode_literals

import autoslug.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general_information', '0001_initial'),
        ('theaters', '0001_initial'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatesEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, verbose_name='Дата и время')),
                ('duration', models.TimeField(blank=True, verbose_name='Продолжительность')),
                ('is_intermission', models.BooleanField(default=False, verbose_name='Есть антракт?')),
                ('count_intermission', models.PositiveIntegerField(blank=True, default=0, verbose_name='Количество антрактов')),
            ],
            options={
                'ordering': ('date_time',),
                'verbose_name_plural': 'Даты проведения',
                'verbose_name': 'Даты проведения',
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='img/thumbnail/', verbose_name='Миниатюра')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('publication_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата публикации')),
                ('content', models.TextField(default='', max_length=6000)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True, verbose_name='Slug')),
                ('link_order', models.CharField(default='', max_length=240, verbose_name='Ссылка на покупку билетов')),
                ('rating', models.FloatField(default=0, verbose_name='Рейтинг')),
                ('top', models.BooleanField(default=False, verbose_name='Выводить в топ?')),
                ('actors', models.ManyToManyField(default='', to='persons.Actors', verbose_name='Актеры')),
                ('age_restrictions', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='general_information.ListAgeRestrictions', verbose_name='Возастное ограничение')),
                ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='general_information.ListCity', verbose_name='Город')),
                ('directors', models.ManyToManyField(default='', to='persons.Directors', verbose_name='Режиссеры')),
                ('genres', models.ManyToManyField(to='general_information.ListGenres', verbose_name='Жанры')),
            ],
            options={
                'verbose_name_plural': 'Спектакли',
                'verbose_name': 'Спектакль',
            },
        ),
        migrations.CreateModel(
            name='PerformanceGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='img/gallery/', verbose_name='Изображения')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performances.Performance')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'Галерея',
                'verbose_name': 'Галерея',
            },
        ),
        migrations.CreateModel(
            name='PerformanceReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата публикации')),
            ],
            options={
                'ordering': ('-publication_date',),
                'verbose_name_plural': 'Отзывы',
                'verbose_name': 'Отзывы',
            },
        ),
        migrations.AddField(
            model_name='performance',
            name='reviews',
            field=models.ManyToManyField(to='performances.PerformanceReviews', verbose_name='Отзывы'),
        ),
        migrations.AddField(
            model_name='performance',
            name='theaters',
            field=models.ManyToManyField(default='', to='theaters.Theaters', verbose_name='Театры'),
        ),
        migrations.AddField(
            model_name='datesevent',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performances.Performance'),
        ),
    ]
