# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performance',
            old_name='theaters',
            new_name='theater',
        ),
    ]
