# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0002_performance_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='img/gallery/', verbose_name='Изображение')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performances.Performance')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галерея',
            },
        ),
    ]
