# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0002_auto_20170418_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='top',
        ),
        migrations.AddField(
            model_name='performance',
            name='top_soon',
            field=models.BooleanField(default=False, verbose_name='Выводить в топ скоро?'),
        ),
        migrations.AddField(
            model_name='performance',
            name='top_today',
            field=models.BooleanField(default=False, verbose_name='Выводить в топ сегодня?'),
        ),
    ]
