# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0003_performancegallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performancegallery',
            old_name='zone',
            new_name='gallery',
        ),
    ]
