# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0003_auto_20170418_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='top_soon',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='top_today',
        ),
        migrations.AddField(
            model_name='performance',
            name='top',
            field=models.CharField(choices=[('not', 'Не выводить'), ('today', 'Сегодня'), ('soon', 'Скоро')], default='not', max_length=6, verbose_name='В какой блок выводить спектакль на главной?'),
        ),
    ]
