# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_information', '0002_auto_20170412_1651'),
        ('performances', '0003_auto_20170413_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='genres',
        ),
        migrations.AddField(
            model_name='performance',
            name='genres',
            field=models.ManyToManyField(to='general_information.ListGenres', verbose_name='Жанры'),
        ),
    ]
