# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_information', '0005_remove_listagerestrictions_city'),
        ('performances', '0004_auto_20170413_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='age_restrictions',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='general_information.ListAgeRestrictions', verbose_name='Возастное ограничение'),
        ),
    ]
