# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0004_auto_20170416_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancegallery',
            name='thumbnail',
            field=models.ImageField(upload_to='img/gallery/', verbose_name='Изображения'),
        ),
    ]
