# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 03:38
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0005_performance_age_restrictions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True, verbose_name='Slug'),
        ),
    ]
