# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0005_auto_20170416_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='link_order',
            field=models.CharField(default='', max_length=240, verbose_name='Ссылка на покупку билетов'),
        ),
    ]
