# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0006_auto_20170415_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
