# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 03:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0007_performance_my_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='my_order',
        ),
    ]
