# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 16:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0007_performance_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Отзывы',
                'verbose_name_plural': 'Отзывы',
                'ordering': ('-publication_date',),
            },
        ),
        migrations.AddField(
            model_name='performance',
            name='reviews',
            field=models.ManyToManyField(to='performances.PerformanceReviews', verbose_name='Отзывы'),
        ),
    ]
