# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0001_initial'),
        ('performances', '0008_remove_performance_my_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='theaters',
            field=models.ManyToManyField(default='', to='theaters.Theaters', verbose_name='Театры'),
        ),
    ]
