# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0008_auto_20170416_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='top',
            field=models.BooleanField(default=False, verbose_name='Выводить в топ?'),
        ),
    ]
