# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_auto_20170415_0429'),
        ('performances', '0009_performance_theaters'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='actors',
            field=models.ManyToManyField(default='', to='actors.Actors', verbose_name='Актеры'),
        ),
    ]
