# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0009_performance_top'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatesEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Дата и время')),
                ('duration', models.TimeField(verbose_name='Продолжительность')),
                ('is_intermission', models.BooleanField(default=False, verbose_name='Есть антракт?')),
                ('count_intermission', models.PositiveIntegerField(default=True, verbose_name='Количество антрактов')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performances.Performance')),
            ],
            options={
                'verbose_name_plural': 'Даты проведения',
                'verbose_name': 'Даты проведения',
            },
        ),
    ]
