# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0014_auto_20170416_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datesevent',
            old_name='gallery',
            new_name='performance',
        ),
        migrations.RenameField(
            model_name='performancegallery',
            old_name='gallery',
            new_name='performance',
        ),
        migrations.AlterField(
            model_name='datesevent',
            name='count_intermission',
            field=models.PositiveIntegerField(blank=True, default=True, verbose_name='Количество антрактов'),
        ),
    ]
