# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0015_auto_20170416_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datesevent',
            name='date_time',
            field=models.DateTimeField(blank=True, verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='datesevent',
            name='duration',
            field=models.TimeField(blank=True, verbose_name='Продолжительность'),
        ),
    ]
