# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 17:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0016_auto_20170416_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datesevent',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='datesevent',
            name='duration',
            field=models.TimeField(auto_now_add=True, verbose_name='Продолжительность'),
        ),
    ]
