# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 09:58
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRestrictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Возрастные ограничения',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Театральные жанры',
            },
        ),
        migrations.CreateModel(
            name='ListAgeRestrictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Название')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True, verbose_name='Slug')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('age_restrictions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_information.AgeRestrictions')),
            ],
            options={
                'verbose_name_plural': 'Список возрастных ограничений',
            },
        ),
        migrations.CreateModel(
            name='ListCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Название')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True, verbose_name='Slug')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_information.City')),
            ],
            options={
                'verbose_name_plural': 'Список Городов',
            },
        ),
        migrations.CreateModel(
            name='ListGenres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Название')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True, verbose_name='Slug')),
                ('genres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_information.Genres')),
            ],
            options={
                'verbose_name_plural': 'Список жанров',
            },
        ),
    ]
