# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_information', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listcity',
            name='city',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='ListCity',
        ),
    ]
