# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listagerestrictions',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='listcity',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='listgenres',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='Название'),
        ),
    ]
