# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_information', '0003_listagerestrictions_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listagerestrictions',
            name='city',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='general_information.ListCity', verbose_name='Город'),
        ),
    ]
