# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_information', '0004_auto_20170414_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listagerestrictions',
            name='city',
        ),
    ]
