# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0003_user_famaly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='famaly',
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general_information.ListCity', verbose_name='Город'),
        ),
    ]
